### ISSUE TITLE
support Swift 2

### ISSUE THREAD

**Issue by narfdotpl** [macoscope/SwiftyStateMachine#11]
- [x] use automatic conversion
- [x] update dependencies (Quick + Nimble)
- [x] make sure tests pass :wink:
- [x] use error handling, `guard`, etc. where it makes sense
- [x] try to provide default graph labels using protocol extensions and enum reflection
- [x] switch to proper Markdown in comments
- [x] test image comments in Xcode 7 (graph PNGs)
- [x] update README with valid Swift 2 (`print`, etc.)

**Comment by bubski** [comment]
:fireworks:
