### ISSUE TITLE
Code executed when leaving/entering a state

### ISSUE THREAD

**Issue by wir349** [macoscope/SwiftyStateMachine#12]
Is there a way to execute a piece of code when leaving/entering a state?

**Comment by narfdotpl** [comment]
There's no dedicated API for this but you can use [`didTransitionCallback`](https://github.com/macoscope/SwiftyStateMachine/blob/350f9a0f5cdd5f3a11bcc6b6a6f03460b20716b8/StateMachine/StateMachine.swift#L94), which receives an old state, an event, and a new state.
