### ISSUE TITLE
pod 'SwiftyStateMachine' not registered in cocoapod index

### ISSUE THREAD

**Issue by mathieutozer** [macoscope/SwiftyStateMachine#26]
pod 'SwiftyStateMachine', '0.3.0' errors when I run pod install saying that it can't find it, and removing the version specification installs version 0.2.0 (which wont compile).

**Comment by narfdotpl** [comment]
Hi Mathieu, 

Yes, sorry for the inconvenience. Version 0.3.0 has not been released yet. As a quick workaround for now, I can recommend using Carthage, or simply copying the two `.swift` files to your repo: https://github.com/macoscope/SwiftyStateMachine/tree/develop/StateMachine. 

I hope to make time to release the new version "soon".

Cheers,
Maciej

**Comment by narfdotpl** [comment]
I don't use CocoaPods but after quick googling I stumbled upon the following way of specifying requirements:

``` ruby
pod 'SwiftyStateMachine', :git => 'https://github.com/macoscope/SwiftyStateMachine.git', :branch => 'develop'
```

Does this work?

**Comment by mathieutozer** [comment]
That worked! Thanks
