### ISSUE TITLE
Consider renaming protocol 'DOTLabelable' to 'DotLabelable'

### ISSUE THREAD

**Issue by DanielAsher** [macoscope/SwiftyStateMachine#3]
I feel PascalCase is appropriate and more readable. Please close this issue if there is strong disagreement.

**Comment by narfdotpl** [comment]
Thanks for pointing this out! I also think PascalCase is more readable, but I prefer to be consistent with Apple's naming (`NSURL`, etc.) and their [guidelines](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingBasics.html):

> [...] method names that start with a well-known acronym, for example, `TIFFRepresentation`

Of course, it's up to debate whether "DOT" is "a well-known acronym"... :wink:

**Comment by DanielAsher** [comment]
I believe we can suggest DOT is not a well-known acronym and refactor for readability :)

**Comment by narfdotpl** [comment]
I'll leave it at "DOT" because it's the proper name of the language. I turned all mentions of it into links: d80d319.
