### ISSUE TITLE
What really are Subjects?

### ISSUE THREAD

**Issue by mauron85** [macoscope/SwiftyStateMachine#32]
Hi, I like this library. But I've problems what and what for are Subjects. Can you share any example how to use them? Many thanks.

**Comment by narfdotpl** [comment]
Sure.

Subjects are objects associated with machines. I use objects that have state machines as properties. These state machines use their "owners" as subjects, so they can act on them. For example in [Glitchy Checkers](http://glitchycheckers.com/) pieces have state machines that can run SpriteKit actions on them:

``` swift
class PieceNode: SKNode {
    lazy var stateMachine: StateMachine<GraphableStateMachineSchema<PieceNodeState, PieceNodeEvent, PieceNode>> = {
        StateMachine(schema: schema, subject: self)
    }()

    // ...
}
```

Schema is defined like this:

``` swift
let schema = // ...
    case .AnimatingRemoving: switch event {
        case .FinishAnimating: return (.Removed, { pieceNode in
            pieceNode.runAction(SKAction.removeFromParent())
        })
        // ...
```

I hope this helps!

**Comment by mauron85** [comment]
That's what I though, but was not sure. Thanks for explanation.

**Comment by narfdotpl** [comment]
✌️
